version: '3.0'
services:
  # app:
  #   image: node:16
  #   #restart: always
  #   container_name: api-secretaria
  #   command: [sh, -c, 'su node -c "npm install && npm run start:dev"']
  #   volumes:
  #     - .:/code
  #   working_dir: /code
  #   env_file: 
  #     - .env
  #   ports:
  #     - "${API_PORT}:${API_PORT}"
  #   depends_on: 
  #     - mariadb
  #   networks:
  #     - escolas-conectadas-net

  db:
    image: mysql
    container_name: service-mysql-web
    #restart: always
    environment:
      MYSQL_DATABASE: "levensoft_db"
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - data-mysql-web:/var/lib/mysql

volumes:
  data-mysql-web:

# networks:
#   escolas-conectadas-net:
#     #name: escolas-conectadas-net
#     driver: bridge
